require('dotenv').config();
const express=require('express');
const app=express();
const cors=require('cors');
const connectDB=require('./config/db');
const projects=require('./routes/projects');
const path=require('path');
connectDB(process.env.MONGODB_URI);
app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:3000'}));
app.use(express.json());
app.use('/uploads',express.static(path.join(__dirname,'uploads')));
app.use('/api/projects',projects);
app.get('/',(req,res)=>res.send('Portfolio API running'));
app.listen(process.env.PORT||5000,()=>console.log('Server running'));